apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-a
  namespace: argocd
spec:
  description: Project A
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'