apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-app1
  namespace: argocd
spec:
  project: project-a
  source:
    repoURL: https://github.com/mellachervudharani07-ops/argocdRbac
    targetRevision: HEAD
    path: project-a/apps/app1
  destination:
    server: https://kubernetes.default.svc
    namespace: dev