apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: project-a-dev
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - app: app1
          - app: app2
  template:
    metadata:
      name: project-a-dev-{{app}}
    spec:
      project: project-a
      source:
        repoURL: https://github.com/mellachervudharani07-ops/argocdRbac
        targetRevision: master
        path: project-a/apps/{{app}}
      destination:
        server: https://kubernetes.default.svc
        namespace: dev
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
