apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.csv: |

    #################################
    # DEV – PROJECT A
    #################################
    p, role:dev-a, applications, get, project-a-*, allow
    p, role:dev-a, applications, list, project-a-*, allow
    p, role:dev-a, applications, watch, project-a-*, allow
    p, role:dev-a, applications, sync, project-a-dev-*, allow
    p, role:dev-a, applications, sync, project-a-staging-*, allow
    p, role:dev-a, applications, override, project-a-dev-*, allow
    p, role:dev-a, applications, override, project-a-staging-*, allow

    #################################
    # SRE – PROJECT A
    #################################
    p, role:sre-a, applications, *, project-a-*, allow
    p, role:sre-a, projects, get, project-a, allow

    #################################
    # DEV – PROJECT B
    #################################
    p, role:dev-b, applications, get, project-b-*, allow
    p, role:dev-b, applications, list, project-b-*, allow
    p, role:dev-b, applications, watch, project-b-*, allow
    p, role:dev-b, applications, sync, project-b-dev-*, allow
    p, role:dev-b, applications, sync, project-b-staging-*, allow
    p, role:dev-b, applications, override, project-b-dev-*, allow
    p, role:dev-b, applications, override, project-b-staging-*, allow

    #################################
    # SRE – PROJECT B
    #################################
    p, role:sre-b, applications, *, project-b-*, allow
    p, role:sre-b, projects, get, project-b, allow

    #################################
    # USER → ROLE MAPPING
    #################################
    g, dev-a, role:dev-a
    g, sre-a, role:sre-a
    g, dev-b, role:dev-b
    g, sre-b, role:sre-b
