apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-b
  namespace: argocd
spec:
  description: Project B Applications
  sourceRepos:
    - https://github.com/mellachervudharani07-ops/argocdRbac

  destinations:
    - namespace: dev
      server: https://kubernetes.default.svc
    - namespace: staging
      server: https://kubernetes.default.svc
    - namespace: prod
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
